'use client'
import Appbar from '../components/Appbar'
import Providers from '@/components/Providers'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Providers>
        <Appbar />
        {children}
      </Providers>
    </>
  )
}
